version: '3.8'

services:
  db:
    image: postgres:15
    container_name: vemusic_db
    restart: always
    environment:
      POSTGRES_USER: vemusic_user
      POSTGRES_PASSWORD: vemusic_password
      POSTGRES_DB: vemusic_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: